spring:
  application:
    name: auth-service
  h2:
    console.enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
